# Site settings
author: Michał Kalbarczyk
title: Software Engineer
email: fazibear@gmail.com
url: http://fazibear.github.io
description: Personal Site

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Build settings
permalink: /blog/:year/:month/:day/:title/

sitemap:
  refresh: false
  priority: 1.0
  changefreq: daily

markdown: kramdown
kramdown:
  input: GFM
