url: http://fazibear.github.io

google_analytics: UA-627863-10
disqus_shortname: fazibear

permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-redirect-from
